language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo test
notifications:
  email:
    on_success: never
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
matrix:
  include:
    - os: osx
      rust: stable
      before_install:
        - export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
        - export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
